name: TickMonitor
version: @version@
main: de.jaylawl.tickmonitor.TickMonitor
api-version: 1.13
authors: [jaylawl]
description: Monitor MSPT performance
website: https://github.com/jaylawl

commands:
  tickmonitor:
    aliases: [tm, mspt]
    permission: "tickmonitor.admin"
    permission-message: "§cInsufficient permission§r"
    description: "See tab-completions for help"