main: de.jaylawl.tickmonitor.Main
name: TickMonitor
version: "2.1.0"
author: jaylawl
website: https://github.com/jaylawl/TickMonitor
description: Monitor MSPT performance
commands:
  tickmonitor:
    aliases: [tm, mspt]
    permission: "tickmonitor.admin"
    permission-message: "§cInsufficient permission§r"
    description: "See tab-completions for help"